=== danpavelka/Znackovaci_jazyky/specifikace_vozidla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="specifikace_vozidla">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vozidlo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vozidlo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Vyrobce"/>
        <xs:element ref="Typ"/>
        <xs:element ref="Pohonne_hmoty"/>
        <xs:element ref="Motor"/>
        <xs:element ref="Vybava"/>
        <xs:element ref="Brzdy"/>
        <xs:element ref="Kola"/>
        <xs:element ref="Cenik"/>
        <xs:element ref="Dodatecne_informace"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vyrobce" type="xs:NCName"/>
  <xs:element name="Typ">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="jmeno"/>
        <xs:element ref="typ_karoserie"/>
        <xs:element ref="material_karoserie"/>
        <xs:element ref="vyska_vozidla"/>
        <xs:element ref="sirka_vozidla"/>
        <xs:element ref="delka_vozidla"/>
        <xs:element ref="rozvor_naprav"/>
        <xs:element ref="objem_kufru"/>
        <xs:element ref="hmotnost"/>
        <xs:element ref="barva"/>
        <xs:element ref="typ_barvy"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="jmeno" type="xs:NCName"/>
  <xs:element name="typ_karoserie" type="xs:NCName"/>
  <xs:element name="material_karoserie" type="xs:NCName"/>
  <xs:element name="vyska_vozidla">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="sirka_vozidla">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="delka_vozidla">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rozvor_naprav">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="objem_kufru">
    <xs:complexType mixed="true">
      <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="hmotnost">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="barva" type="xs:NCName"/>
  <xs:element name="typ_barvy">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="oznaceni_barvy" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Pohonne_hmoty">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="palivo"/>
        <xs:element ref="spotreba"/>
        <xs:element ref="objem_nadrze"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="palivo">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="doporucene" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="spotreba">
    <xs:complexType mixed="true">
      <xs:attribute name="jednotky" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="objem_nadrze">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Motor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="druh"/>
        <xs:element ref="oznaceni"/>
        <xs:element ref="objem"/>
        <xs:element ref="pocet__valcu"/>
        <xs:element ref="max_vykon"/>
        <xs:element ref="max_otacky"/>
        <xs:element ref="max_tocivy_moment"/>
        <xs:element ref="exhalacni_norma"/>
        <xs:element ref="emise"/>
        <xs:element ref="max_rychlost"/>
        <xs:element ref="zrychleni"/>
        <xs:element ref="pocet_stupnu"/>
        <xs:element ref="spojka"/>
        <xs:element ref="nahon"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="druh" type="xs:NCName"/>
  <xs:element name="oznaceni" type="xs:NCName"/>
  <xs:element name="objem">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="pocet__valcu" type="xs:integer"/>
  <xs:element name="max_vykon">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="max_otacky" type="xs:NMTOKEN"/>
  <xs:element name="max_tocivy_moment">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="exhalacni_norma" type="xs:NCName"/>
  <xs:element name="emise">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="max_rychlost">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="zrychleni">
    <xs:complexType mixed="true">
      <xs:attribute name="rozmezi" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pocet_stupnu">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="typ_prevodovky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="spojka">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="typ_ovladani" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="nahon">
    <xs:complexType mixed="true">
      <xs:attribute name="pocet_pohanenych_kol" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vybava">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ_vybavy"/>
        <xs:element ref="barva_interieru"/>
        <xs:element ref="signalizace_pri_parkovani"/>
        <xs:element ref="klimatizace"/>
        <xs:element ref="tempomat"/>
        <xs:element ref="vyhrivani_sedadel"/>
        <xs:element ref="typ_svetlometu"/>
        <xs:element ref="autoradio"/>
        <xs:element ref="palubni_pocitac"/>
        <xs:element ref="abs"/>
        <xs:element ref="asr"/>
        <xs:element ref="esp"/>
        <xs:element ref="tazne_zarizeni"/>
        <xs:element ref="mlhovky"/>
        <xs:element ref="lane_assist"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typ_vybavy" type="xs:NCName"/>
  <xs:element name="barva_interieru" type="xs:NCName"/>
  <xs:element name="signalizace_pri_parkovani" type="xs:NCName"/>
  <xs:element name="klimatizace">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="vyrobce" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="tempomat" type="xs:NCName"/>
  <xs:element name="vyhrivani_sedadel" type="xs:NCName"/>
  <xs:element name="typ_svetlometu" type="xs:NCName"/>
  <xs:element name="autoradio" type="xs:NCName"/>
  <xs:element name="palubni_pocitac" type="xs:NCName"/>
  <xs:element name="abs" type="xs:NCName"/>
  <xs:element name="asr" type="xs:NCName"/>
  <xs:element name="esp" type="xs:NCName"/>
  <xs:element name="tazne_zarizeni">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="nadstandard" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="mlhovky">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="nadstandard" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="lane_assist">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="nadstandard" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Brzdy">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ_brzd"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typ_brzd" type="xs:NCName"/>
  <xs:element name="Kola">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="standardni_kola"/>
        <xs:element ref="nadstandardni_kola"/>
        <xs:element ref="material"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="standardni_kola">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="rozmer" use="required" type="xs:integer"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="nadstandardni_kola">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="rozmer" use="required" type="xs:integer"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="material" type="xs:string"/>
  <xs:element name="Cenik">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="celkova_cena"/>
        <xs:element ref="cena_nadstandardni_vybavy"/>
        <xs:element ref="cena_metalicke_barvy"/>
        <xs:element ref="cena_kol"/>
        <xs:element ref="na_splatky"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="celkova_cena">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="mena" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="cena_nadstandardni_vybavy">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="mena" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="cena_metalicke_barvy">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="mena" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="cena_kol" type="xs:integer"/>
  <xs:element name="na_splatky" type="xs:NCName"/>
  <xs:element name="Dodatecne_informace">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ujeto"/>
        <xs:element ref="rok_vyroby"/>
        <xs:element ref="bourano"/>
        <xs:element ref="osobni_vlastnictvi"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ujeto">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="rok_vyroby" type="xs:integer"/>
  <xs:element name="bourano" type="xs:NCName"/>
  <xs:element name="osobni_vlastnictvi" type="xs:NCName"/>
</xs:schema>

=== danpavelka/Znackovaci_jazyky/specifikace_vozidla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="specifikace_vozidla.xsl"?>
<specifikace_vozidla> <!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="specifikace_vozidla.xsd">-->
<vozidlo>
    <Vyrobce>Skoda</Vyrobce>
    <Typ>
        <jmeno>Octavia</jmeno>
        <typ_karoserie>Sedan</typ_karoserie>
        <material_karoserie>Hlinik</material_karoserie>
        <vyska_vozidla jednotky="mm">1461</vyska_vozidla>
        <sirka_vozidla jednotky="mm">2017</sirka_vozidla>
        <delka_vozidla jednotky="mm">4659</delka_vozidla>
        <rozvor_naprav jednotky="mm">2686</rozvor_naprav>
        <objem_kufru jednotky="l">590/1580</objem_kufru>
        <hmotnost jednotky="kg">1342</hmotnost>
        <barva>Modra</barva>
        <typ_barvy oznaceni_barvy="race">Metaliza</typ_barvy>
    </Typ>
       
    <Pohonne_hmoty>
        <palivo doporucene="oktanove cislo min. 95">Benzin</palivo>
        <spotreba jednotky="l/100km">5,9</spotreba>
        <objem_nadrze jednotky="l">50</objem_nadrze>
    </Pohonne_hmoty>
    
    <Motor>
        <druh>Zazehovy</druh>
        <oznaceni>TSI</oznaceni>
        <objem jednotky="cm^3">1798</objem>
        <pocet__valcu>4</pocet__valcu>
        <max_vykon jednotky="kW">132</max_vykon>
        <max_otacky>5100-6200</max_otacky>
        <max_tocivy_moment jednotky="nM">250</max_tocivy_moment>
        <exhalacni_norma>EU6</exhalacni_norma>
        <emise jednotky="g/km">136</emise>
        <max_rychlost jednotky="km/h">229</max_rychlost>
        <zrychleni rozmezi="0-100km/h">7,3</zrychleni>
        <pocet_stupnu typ_prevodovky="manualni">6</pocet_stupnu>
        <spojka typ_ovladani="hydraulicky">Jednokotoucova</spojka>
        <nahon pocet_pohanenych_kol="2">Predni kola</nahon>        
    </Motor>
    
    <Vybava>
        
    </Vybava>
    
    <Brzdy>
        
    </Brzdy>
    
    <Kola>
        
    </Kola>
    
    <Cenik>
        
    </Cenik>
    
    <Zapujceni>
        
    </Zapujceni>
    
    <Dodatecne_informace>
        
    </Dodatecne_informace>
    
</vozidlo>
</specifikace_vozidla>
